[program:full_dev_10m_s1338_baseline]
directory=/workspace/repo/nanoGPT
command=/workspace/envs/nanogpt/bin/python eval/full_dev_loss.py --checkpoint out-babylm/bl10m-d512L32-do0.1-gate-offdev-aoaw19-aoat20-u37-b8ga64-s1338/ckpt_final-w0090M-i000471.pt --data-dir data/babylm_officialdev --output-json results/full_dev_loss/bl10m-d512L32-do0.1-gate-offdev-aoaw19-aoat20-u37-b8ga64-s1338.json
environment=CUDA_VISIBLE_DEVICES="0",PYTHONUNBUFFERED="1"
autostart=false
autorestart=false
startsecs=0
stdout_logfile=/workspace/repo/nanoGPT/logs/full-dev-loss/bl10m-d512L32-do0.1-gate-offdev-aoaw19-aoat20-u37-b8ga64-s1338.log
redirect_stderr=true
stdout_logfile_maxbytes=0

[program:full_dev_10m_s1338_attnres]
directory=/workspace/repo/nanoGPT
command=/workspace/envs/nanogpt/bin/python eval/full_dev_loss.py --checkpoint out-babylm/bl10m-d512L32-do0.1-gate-attnres8-offdev-aoaw19-aoat20-u37-b8ga64-s1338/ckpt_final-w0090M-i000471.pt --data-dir data/babylm_officialdev --output-json results/full_dev_loss/bl10m-d512L32-do0.1-gate-attnres8-offdev-aoaw19-aoat20-u37-b8ga64-s1338.json
environment=CUDA_VISIBLE_DEVICES="1",PYTHONUNBUFFERED="1"
autostart=false
autorestart=false
startsecs=0
stdout_logfile=/workspace/repo/nanoGPT/logs/full-dev-loss/bl10m-d512L32-do0.1-gate-attnres8-offdev-aoaw19-aoat20-u37-b8ga64-s1338.log
redirect_stderr=true
stdout_logfile_maxbytes=0

[program:full_dev_10m_s1339_baseline]
directory=/workspace/repo/nanoGPT
command=/workspace/envs/nanogpt/bin/python eval/full_dev_loss.py --checkpoint out-babylm/bl10m-d512L32-do0.1-gate-offdev-aoaw19-aoat20-u37-b8ga64-s1339/ckpt_final-w0090M-i000471.pt --data-dir data/babylm_officialdev --output-json results/full_dev_loss/bl10m-d512L32-do0.1-gate-offdev-aoaw19-aoat20-u37-b8ga64-s1339.json
environment=CUDA_VISIBLE_DEVICES="2",PYTHONUNBUFFERED="1"
autostart=false
autorestart=false
startsecs=0
stdout_logfile=/workspace/repo/nanoGPT/logs/full-dev-loss/bl10m-d512L32-do0.1-gate-offdev-aoaw19-aoat20-u37-b8ga64-s1339.log
redirect_stderr=true
stdout_logfile_maxbytes=0

[program:full_dev_10m_s1339_attnres]
directory=/workspace/repo/nanoGPT
command=/workspace/envs/nanogpt/bin/python eval/full_dev_loss.py --checkpoint out-babylm/bl10m-d512L32-do0.1-gate-attnres8-offdev-aoaw19-aoat20-u37-b8ga64-s1339/ckpt_final-w0090M-i000471.pt --data-dir data/babylm_officialdev --output-json results/full_dev_loss/bl10m-d512L32-do0.1-gate-attnres8-offdev-aoaw19-aoat20-u37-b8ga64-s1339.json
environment=CUDA_VISIBLE_DEVICES="3",PYTHONUNBUFFERED="1"
autostart=false
autorestart=false
startsecs=0
stdout_logfile=/workspace/repo/nanoGPT/logs/full-dev-loss/bl10m-d512L32-do0.1-gate-attnres8-offdev-aoaw19-aoat20-u37-b8ga64-s1339.log
redirect_stderr=true
stdout_logfile_maxbytes=0
